=== Denthor99/BDsms/Editorial/editorial.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="editorial" type="editorialInforme"/>
        <xs:complexType name="editorialInforme">
            <xs:sequence>
                <xs:element name="informe" type="informe_tabla"></xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="informe_tabla">
            <xs:sequence>
                <xs:element name="cabecera_informe" type="cabeceraInforme"/>
                <xs:element name="datos_informe" type="datosInforme"/>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="cabeceraInforme">
            <xs:sequence>
                <xs:element name="nombre_editorial" type="xs:string"/>
                <xs:element name="nombre_informe" type="xs:string"/>
                <xs:element name="descripcion" type="xs:string"/>
                <xs:element name="fecha_informe" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="datosInforme">
            <xs:sequence>
                <xs:element name="region" type="regionesInforme"/>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="regionesInforme" mixed="true">
            <xs:sequence>
                <xs:element name="norte" type="norteInforme"/>
                <xs:element name="centro" type="centroInforme"/>
                <xs:element name="sur" type="surInforme"/>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="norteInforme" mixed="true">
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="trimestre" type="TrimestreInforme" maxOccurs="4"/>
                    <xs:element name="librosVendidos" type="xs:string" default="NO_INFO"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="centroInforme" mixed="true">
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="trimestre" type="TrimestreInforme" maxOccurs="4"/>
                    <xs:element name="librosVendidos" type="xs:string" default="NO_INFO"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="surInforme" mixed="true">
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="trimestre" type="TrimestreInforme" maxOccurs="4"/>
                    <xs:element name="librosVendidos" type="xs:string" default="NO_INFO"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:simpleType name="TrimestreInforme">
            <xs:restriction base="xs:positiveInteger">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="4"/>
            </xs:restriction>
        </xs:simpleType>
</xs:schema>

=== Denthor99/BDsms/Editorial/editorialXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<editorial xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="editorial.xsd">
    <informe>
        <cabecera_informe>
            <nombre_editorial>Ediciones Aranda</nombre_editorial>
            <nombre_informe>Informe regional de ventas</nombre_informe>
            <descripcion>informe de ventas para las regiones Norte, Centro y Sur</descripcion>
            <fecha_informe>2009-12-30</fecha_informe>
        </cabecera_informe>
        <datos_informe>
            <region>
                <norte>Norte
                    <trimestre>1</trimestre>
                    <librosVendidos>24000</librosVendidos>
                    <trimestre>2</trimestre>
                    <librosVendidos>38600</librosVendidos>
                    <trimestre>3</trimestre>
                    <librosVendidos>NO_INFO</librosVendidos>
                    <trimestre>4</trimestre>
                    <librosVendidos>NO_INFO</librosVendidos>
                </norte>
                <centro>Centro
                    <trimestre>1</trimestre>
                    <librosVendidos>NO_INFO</librosVendidos>
                    <trimestre>2</trimestre>
                    <librosVendidos>16080</librosVendidos>
                    <trimestre>3</trimestre>
                    <librosVendidos>25000</librosVendidos>
                    <trimestre>4</trimestre>
                    <librosVendidos>29000</librosVendidos>
                </centro>
                <sur>Sur
                    <trimestre>1</trimestre>
                    <librosVendidos>27000</librosVendidos>
                    <trimestre>2</trimestre>
                    <librosVendidos>31400</librosVendidos>
                    <trimestre>3</trimestre>
                    <librosVendidos>40100</librosVendidos>
                    <trimestre>4</trimestre>
                    <librosVendidos>30000</librosVendidos>
                </sur>
            </region>
        </datos_informe>
    </informe>
</editorial>
