=== Denthor99/BDsms/Clientes/Clientes.dtd
<!ELEMENT Clientes (Sede*)>
<!ELEMENT Sede (direccion+,nom_empleado,fech_alta,cliente*)>
<!ATTLIST Sede codigo CDATA #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nom_empleado (#PCDATA)>
<!ELEMENT fech_alta (#PCDATA)>
<!ELEMENT cliente (desCliente,numero,vivienda+)>
<!ATTLIST cliente codigo CDATA #REQUIRED>
<!ELEMENT desCliente (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT vivienda (coste, resumen, plazo)>
<!ATTLIST vivienda id CDATA #REQUIRED>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== Denthor99/BDsms/Clientes/ClientesDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Clientes SYSTEM "Clientes.dtd">
<Clientes>
    <Sede codigo="B453-564">
        <direccion>Calle La Oliva s/n, Jerez de la Frontera</direccion>
        <nom_empleado>Roberto Robles</nom_empleado>
        <fech_alta>2023/01/14</fech_alta>
        <cliente codigo="KRE-334">
            <desCliente>Solvente</desCliente>
            <numero>2</numero>
            <vivienda id="001">
                <coste>120000</coste>
                <resumen>Piso a las afueras de Valencia</resumen>
                <plazo>2022/10/29</plazo>
            </vivienda>
            <vivienda id="002">
                <coste>480000</coste>
                <resumen>Pequeño Chalet con dos plantas y garage, cuenta con </resumen>
                <plazo>1999/04/15</plazo>
            </vivienda>
        </cliente>
    </Sede>
    <Sede codigo="R561-780">
        <direccion>Calle Padre Luis Nº4, Algeciras</direccion>
        <nom_empleado>Pepe Viyuela</nom_empleado>
        <fech_alta>2022/03/23</fech_alta>
        <cliente codigo="DAN-948">
            <desCliente>Insolvente</desCliente>
            <numero>1</numero>
            <vivienda id="003">
                <coste>950000</coste>
                <resumen>Chalet de tres plantas con un gran jardín, piscina y helipuerto</resumen>
                <plazo>2007/01/31</plazo>
            </vivienda>
        </cliente>
    </Sede>
</Clientes>
